import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Footer from "./components/Footer";
import Navbar from "./components/Header";
import { AxiosContextProvider } from "@/context/AxiosContext";
import { Toaster } from "@/components/ui/toaster";
import { CloudProvider } from "./learn/components/cloud/useCloud";
import { ConfigProvider } from "@/hooks/useConfig";
import { ConnectionProvider } from "@/hooks/useConnection";
import { ToastProvider } from "@radix-ui/react-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <ConnectionProvider>
            <ConfigProvider>
              <CloudProvider>
                <AxiosContextProvider>
                  <AuthProvider>
                    <Navbar />
                    {children}
                    <Footer />
                    <Toaster />
                  </AuthProvider>
                </AxiosContextProvider>
              </CloudProvider>
            </ConfigProvider>
          </ConnectionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
