import { FC } from "react";
interface countryCode {
  [key: string]: {
    flag: string;
    code: string;
  };
}
export const countryCodesObject: countryCode = {
  CA: { flag: "🇨🇦", code: "+1" },
  US: { flag: "🇺🇸", code: "+1" },
  BS: { flag: "🇧🇸", code: "+1-242" },
  BB: { flag: "🇧🇧", code: "+1-246" },
  AI: { flag: "🇦🇮", code: "+1-264" },
  AG: { flag: "🇦🇬", code: "+1-268" },
  KY: { flag: "🇰🇾", code: "+1-345" },
  BM: { flag: "🇧🇲", code: "+1-441" },
  GD: { flag: "🇬🇩", code: "+1-473" },
  TC: { flag: "🇹🇨", code: "+1-649" },
  MS: { flag: "🇲🇸", code: "+1-664" },
  MP: { flag: "🇲🇵", code: "+1-670" },
  GU: { flag: "🇬🇺", code: "+1-671" },
  AS: { flag: "🇦🇸", code: "+1-684" },
  SX: { flag: "🇸🇽", code: "+1-721" },
  LC: { flag: "🇱🇨", code: "+1-758" },
  DM: { flag: "🇩🇲", code: "+1-767" },
  VC: { flag: "🇻🇨", code: "+1-784" },
  PR: { flag: "🇵🇷", code: "+1-787" },
  DO: { flag: "🇩🇴", code: "+1-809" },
  TT: { flag: "🇹🇹", code: "+1-868" },
  KN: { flag: "🇰🇳", code: "+1-869" },
  JM: { flag: "🇯🇲", code: "+1-876" },
  EG: { flag: "🇪🇬", code: "+20" },
  MA: { flag: "🇲🇦", code: "+212" },
  DZ: { flag: "🇩🇿", code: "+213" },
  TN: { flag: "🇹🇳", code: "+216" },
  LY: { flag: "🇱🇾", code: "+218" },
  GM: { flag: "🇬🇲", code: "+220" },
  SN: { flag: "🇸🇳", code: "+221" },
  MR: { flag: "🇲🇷", code: "+222" },
  ML: { flag: "🇲🇱", code: "+223" },
  GN: { flag: "🇲🇱", code: "+224" },
  CI: { flag: "🇨🇮", code: "+225" },
  BF: { flag: "🇧🇫", code: "+226" },
  NE: { flag: "🇳🇪", code: "+227" },
  TG: { flag: "🇹🇬", code: "+228" },
  BJ: { flag: "🇧🇯", code: "+229" },
  MU: { flag: "🇲🇺", code: "+230" },
  LR: { flag: "🇱🇷", code: "+231" },
  SL: { flag: "🇸🇱", code: "+232" },
  GH: { flag: "🇬🇭", code: "+233" },
  NG: { flag: "🇳🇬", code: "+234" },
  TD: { flag: "🇹🇩", code: "+235" },
  CF: { flag: "🇨🇫", code: "+236" },
  CM: { flag: "🇨🇲", code: "+237" },
  CV: { flag: "🇨🇻", code: "+238" },
  ST: { flag: "🇸🇹", code: "+239" },
  GQ: { flag: "🇬🇶", code: "+240" },
  GA: { flag: "🇲🇬", code: "+241" },
  CG: { flag: "🇨🇬", code: "+242" },
  CD: { flag: "🇨🇩", code: "+243" },
  AO: { flag: "🇦🇴", code: "+244" },
  GW: { flag: "🇬🇼", code: "+245" },
  IO: { flag: "🇮🇴", code: "+246" },
  SC: { flag: "🇸🇨", code: "+248" },
  SD: { flag: "🇸🇩", code: "+249" },
  RW: { flag: "🇷🇼", code: "+250" },
  ET: { flag: "🇪🇹", code: "+251" },
  SO: { flag: "🇸🇴", code: "+252" },
  DJ: { flag: "🇩🇯", code: "+253" },
  KE: { flag: "🇰🇪", code: "+254" },
  TZ: { flag: "🇹🇿", code: "+255" },
  UG: { flag: "🇺🇬", code: "+256" },
  BI: { flag: "🇧🇮", code: "+257" },
  MZ: { flag: "🇲🇿", code: "+258" },
  ZM: { flag: "🇿🇲", code: "+260" },
  MG: { flag: "🇲🇬", code: "+261" },
  TF: { flag: "🇹🇫", code: "+262" },
  YT: { flag: "🇾🇹", code: "+262" },
  ZW: { flag: "🇿🇼", code: "+263" },
  NA: { flag: "🇳🇦", code: "+264" },
  MW: { flag: "🇲🇼", code: "+265" },
  LS: { flag: "🇱🇸", code: "+266" },
  BW: { flag: "🇧🇼", code: "+267" },
  SZ: { flag: "🇸🇿", code: "+268" },
  KM: { flag: "🇰🇲", code: "+269" },
  ZA: { flag: "🇿🇦", code: "+27" },
  SH: { flag: "🇸🇭", code: "+290" },
  ER: { flag: "🇪🇷", code: "+291" },
  AW: { flag: "🇦🇼", code: "+297" },
  FO: { flag: "🇫🇴", code: "+298" },
  GL: { flag: "🇬🇱", code: "+299" },
  GR: { flag: "🇬🇷", code: "+30" },
  NL: { flag: "🇳🇱", code: "+31" },
  BE: { flag: "🇧🇪", code: "+32" },
  FR: { flag: "🇫🇷", code: "+33" },
  ES: { flag: "🇪🇸", code: "+34" },
  GI: { flag: "🇬🇮", code: "+350" },
  PT: { flag: "🇵🇹", code: "+351" },
  LU: { flag: "🇱🇺", code: "+352" },
  IE: { flag: "🇮🇪", code: "+353" },
  IS: { flag: "🇮🇸", code: "+354" },
  AL: { flag: "🇦🇱", code: "+355" },
  MT: { flag: "🇲🇹", code: "+356" },
  CY: { flag: "🇨🇾", code: "+357" },
  AX: { flag: "🇦🇽", code: "+358" },
  FI: { flag: "🇫🇮", code: "+358" },
  BG: { flag: "🇧🇬", code: "+359" },
  HU: { flag: "🇭🇺", code: "+36" },
  LT: { flag: "🇱🇹", code: "+370" },
  LV: { flag: "🇱🇻", code: "+371" },
  EE: { flag: "🇪🇪", code: "+372" },
  MD: { flag: "🇲🇩", code: "+373" },
  AM: { flag: "🇦🇲", code: "+374" },
  BY: { flag: "🇧🇾", code: "+375" },
  AD: { flag: "🇦🇩", code: "+376" },
  MC: { flag: "🇲🇨", code: "+377" },
  SM: { flag: "🇸🇲", code: "+378" },
  VA: { flag: "🇻🇦", code: "+379" },
  UA: { flag: "🇺🇦", code: "+380" },
  RS: { flag: "🇷🇸", code: "+381" },
  ME: { flag: "🇲🇪", code: "+382" },
  XK: { flag: "🇽🇰", code: "+383" },
  HR: { flag: "🇭🇷", code: "+385" },
  SI: { flag: "🇸🇮", code: "+386" },
  BA: { flag: "🇧🇦", code: "+387" },
  MK: { flag: "🇲🇰", code: "+389" },
  IT: { flag: "🇮🇹", code: "+39" },
  RO: { flag: "🇷🇴", code: "+40" },
  CH: { flag: "🇨🇭", code: "+41" },
  CZ: { flag: "🇨🇿", code: "+420" },
  SK: { flag: "🇸🇰", code: "+421" },
  LI: { flag: "🇱🇮", code: "+423" },
  AT: { flag: "🇦🇹", code: "+43" },
  GG: { flag: "🇬🇬", code: "+44" },
  IM: { flag: "🇮🇲", code: "+44" },
  JE: { flag: "🇯🇪", code: "+44" },
  GB: { flag: "🇬🇧", code: "+44" },
  DK: { flag: "🇩🇰", code: "+45" },
  SE: { flag: "🇸🇪", code: "+46" },
  BV: { flag: "🇧🇻", code: "+47" },
  NO: { flag: "🇳🇴", code: "+47" },
  SJ: { flag: "🇸🇯", code: "+47" },
  PL: { flag: "🇵🇱", code: "+48" },
  DE: { flag: "🇩🇪", code: "+49" },
  FK: { flag: "🇲🇸", code: "+500" },
  BZ: { flag: "🇧🇿", code: "+501" },
  GT: { flag: "🇵🇪", code: "+502" },
  SV: { flag: "🇸🇻", code: "+503" },
  HN: { flag: "🇭🇳", code: "+504" },
  NI: { flag: "🇳🇮", code: "+505" },
  CR: { flag: "🇨🇷", code: "+506" },
  PA: { flag: "🇵🇦", code: "+507" },
  PM: { flag: "🇸🇵", code: "+508" },
  HT: { flag: "🇭🇹", code: "+509" },
  PE: { flag: "🇵🇪", code: "+51" },
  MX: { flag: "🇲🇽", code: "+52" },
  CU: { flag: "🇨🇺", code: "+53" },
  AR: { flag: "🇦🇷", code: "+54" },
  BR: { flag: "🇧🇷", code: "+55" },
  CL: { flag: "🇨🇱", code: "+56" },
  CO: { flag: "🇨🇴", code: "+57" },
  VE: { flag: "🇻🇪", code: "+58" },
  GP: { flag: "🇲🇫", code: "+590" },
  BL: { flag: "🇧🇱", code: "+590" },
  MF: { flag: "🇲🇵", code: "+590" },
  BO: { flag: "🇧🇴", code: "+591" },
  GY: { flag: "🇬🇾", code: "+592" },
  EC: { flag: "🇪🇨", code: "+593" },
  GF: { flag: "🇬🇫", code: "+594" },
  PY: { flag: "🇵🇾", code: "+595" },
  MQ: { flag: "🇲🇶", code: "+596" },
  SR: { flag: "🇸🇷", code: "+597" },
  UY: { flag: "🇺🇾", code: "+598" },
  BQ: { flag: "🇧🇶", code: "+599" },
  CW: { flag: "🇨🇼", code: "+599" },
  MY: { flag: "🇲🇾", code: "+60" },
  AU: { flag: "🇦🇺", code: "+61" },
  CX: { flag: "🇨🇽", code: "+61" },
  CC: { flag: "🇨🇨", code: "+61" },
  ID: { flag: "🇮🇩", code: "+62" },
  PH: { flag: "🇵🇭", code: "+63" },
  NZ: { flag: "🇳🇿", code: "+64" },
  PN: { flag: "🇵🇳", code: "+64" },
  SG: { flag: "🇸🇬", code: "+65" },
  TH: { flag: "🇹🇭", code: "+66" },
  TL: { flag: "🇹🇱", code: "+670" },
  AQ: { flag: "🇦🇶", code: "+672" },
  NF: { flag: "🇳🇫", code: "+672" },
  BN: { flag: "🇧🇳", code: "+673" },
  NR: { flag: "🇳🇷", code: "+674" },
  PG: { flag: "🇵🇬", code: "+675" },
  TO: { flag: "🇹🇴", code: "+676" },
  SB: { flag: "🇸🇧", code: "+677" },
  VU: { flag: "🇻🇺", code: "+678" },
  FJ: { flag: "🇫🇯", code: "+679" },
  PW: { flag: "🇵🇼", code: "+680" },
  WF: { flag: "🇼🇫", code: "+681" },
  CK: { flag: "🇨🇰", code: "+682" },
  NU: { flag: "🇳🇺", code: "+683" },
  WS: { flag: "🇼🇸", code: "+685" },
  KI: { flag: "🇰🇮", code: "+686" },
  NC: { flag: "🇳🇨", code: "+687" },
  TV: { flag: "🇹🇻", code: "+688" },
  PF: { flag: "🇵🇫", code: "+689" },
  TK: { flag: "🇹🇰", code: "+690" },
  FM: { flag: "🇫🇲", code: "+691" },
  MH: { flag: "🇲🇭", code: "+692" },
  KZ: { flag: "🇰🇿", code: "+7" },
  RU: { flag: "🇷🇺", code: "+7" },
  JP: { flag: "🇯🇵", code: "+81" },
  KR: { flag: "🇰🇷", code: "+82" },
  VN: { flag: "🇻🇳", code: "+84" },
  HK: { flag: "🇭🇰", code: "+852" },
  MO: { flag: "🇲🇴", code: "+853" },
  KH: { flag: "🇰🇭", code: "+855" },
  LA: { flag: "🇱🇦", code: "+856" },
  CN: { flag: "🇨🇳", code: "+86" },
  BD: { flag: "🇧🇩", code: "+880" },
  TW: { flag: "🇹🇼", code: "+886" },
  TR: { flag: "🇹🇷", code: "+90" },
  IN: { flag: "🇮🇳", code: "+91" },
  PK: { flag: "🇵🇰", code: "+92" },
  LK: { flag: "🇱🇰", code: "+94" },
  MM: { flag: "🇲🇲", code: "+95" },
  MV: { flag: "🇲🇻", code: "+960" },
  LB: { flag: "🇱🇧", code: "+961" },
  JO: { flag: "🇯🇴", code: "+962" },
  SY: { flag: "🇸🇾", code: "+963" },
  IQ: { flag: "🇮🇶", code: "+964" },
  KW: { flag: "🇰🇼", code: "+965" },
  SA: { flag: "🇸🇦", code: "+966" },
  YE: { flag: "🇾🇪", code: "+967" },
  OM: { flag: "🇴🇲", code: "+968" },
  PS: { flag: "🇵🇸", code: "+970" },
  AE: { flag: "🇦🇪", code: "+971" },
  IL: { flag: "🇮🇱", code: "+972" },
  BH: { flag: "🇧🇭", code: "+973" },
  QA: { flag: "🇶🇦", code: "+974" },
  BT: { flag: "🇧🇹", code: "+975" },
  MN: { flag: "🇲🇳", code: "+976" },
  NP: { flag: "🇳🇵", code: "+977" },
  IR: { flag: "🇮🇷", code: "+98" },
  TJ: { flag: "🇹🇯", code: "+992" },
  TM: { flag: "🇹🇲", code: "+993" },
  AZ: { flag: "🇦🇿", code: "+994" },
  GE: { flag: "🇬🇪", code: "+995" },
  KG: { flag: "🇰🇬", code: "+996" },
  UZ: { flag: "🇺🇿", code: "+998" },
};

const CountryCode: FC = () => {
  return (
    <>
      {Object.keys(countryCodesObject).map(
        (ele: Extract<keyof countryCode, string>, index) => {
          const currCountry = countryCodesObject[ele];
          return (
            <option value={currCountry.code} key={index}>
              {currCountry.code} {currCountry.flag}
            </option>
          );
        }
      )}
    </>
  );
};

export default CountryCode;
